version: '3'
services:
  frontend:
    image: frontend:latest  # Replace with your actual frontend image name
    ports:
      - "4040:4173"
    environment:
      - VITE_API_URL=http://localhost:3001
      - VITE_WEBSOCKET_URL=ws://localhost:8080

  backend:
    image: backend:latest  # Replace with your actual backend image name
    ports:
      - "3001:3001"
      - "8080:8080"
    environment:
      - DATABASE_URL=file:./dev.db
      - OPENAI_API_KEY=sk-...
